name: test-CI

on:
  release:
    types: [created]  # 当新建 Release 时触发
  workflow_dispatch:  # 手动触发（可选）
  
jobs:
  build:
    name: Build asuswrt firmware for Tenda AC9 Router
    runs-on: ubuntu-latest
    
    # 确保只有仓库所有者可以触发
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Prepare artifact
      run: |
        mkdir -p ${{ github.workspace }}/artifact/firmware
        mkdir -p ${{ github.workspace }}/release/src-rt-9.x/src/image
        touch ${{ github.workspace }}/release/src-rt-9.x/src/image/test.txt
        echo "hello world" > ${{ github.workspace }}/release/src-rt-9.x/src/image/test.txt
        cp -f $(find ${{ github.workspace }}/release/src-rt-9.x/src/image/ -type f) ${{ github.workspace }}/artifact/firmware/
        ls -l ${{ github.workspace }}/artifact/firmware/
    
    - name: Upload release asset
      # 确保只在 release 事件时执行
      # if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/artifact/firmware/*
        tag: ${{ github.ref }}
        file_glob: true
